---

- name: Add core development packages
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop:
    - base-devel
    - zlib
    - libffi
    - openssl
    - bzip2
    - readline
    - sqlite
    - xz

- name: Add utility programs
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop: "{{ pacman_programs | default([]) }}"
