---
- name: Ensure claude-code is installed
  command: command -v claude
  register: claude_result

- name: Ensure MCP servers are connected to claude
  ansible.builtin.shell:
    cmd: claude mcp add --transport {{ item.transport }} {{ item.name }} {{ item.url }} {{ item.extras }}
  ignore_errors: true
  loop: "{{ mcps }}"
  changed_when: false